name: Install dependencies

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      node:
        required: true
        type: string

permissions:
  contents: read

jobs:
  prepare_cache:
    name: Prepare yarn cache for ${{ inputs.os }} on Node v${{ inputs.node }}
    runs-on: ${{ inputs.os }}

    steps:
      - name: Checkout üõéÔ∏è
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 20
          fetch-tags: false

      - name: Restore cached node modules ‚ôªÔ∏è
        id: cache-yarn
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4
        with:
          path: |
            .yarn/cache
            node_modules
            examples/example-app-monorepo/node_modules
            examples/example-app-v17/node_modules
            examples/example-app-v18/node_modules
            examples/example-app-v19/node_modules
            examples/example-app-yarn-workspace/node_modules
          key: ${{ inputs.os }}-${{ inputs.node }}-build-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ inputs.os }}-${{ inputs.node }}-build

      - name: Setup Node version ‚öôÔ∏è
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        if: ${{ steps.cache-yarn.outputs.cache-hit != 'true' }}
        with:
          node-version: ${{ inputs.node }}

      - name: Install üîß
        if: ${{ steps.cache-yarn.outputs.cache-hit != 'true' }}
        run: |
          yarn --immutable
          yarn --cwd examples/example-app-monorepo
          yarn --cwd examples/example-app-v17
          yarn --cwd examples/example-app-v18
          yarn --cwd examples/example-app-v19
          yarn --cwd examples/example-app-yarn-workspace
