name: PR codes check ğŸ”

on:
  pull_request:
    branches:
      - '**'
    paths:
      - '**/*'
      - '!website/**/*'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  prepare-cache:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [18.x, 20.x, 22.x]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
        with:
          fetch-depth: 20
          fetch-tags: false

      - name: Setup codespace for ${{ matrix.os }} on Node v${{ matrix.node-version }} âš™ï¸
        uses: ./.github/actions/setup-codespace
        with:
          node-version: ${{ matrix.node-version }}
          os: ${{ matrix.os }}

  test-code-quality:
    needs: prepare-cache
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
        with:
          fetch-depth: 20
          fetch-tags: false

      - name: Setup codespace âš™ï¸
        uses: ./.github/actions/setup-codespace
        with:
          node-version: ${{ matrix.node-version }}
          os: ${{ matrix.os }}

      - name: Run check commit convention ğŸ”ï¸
        run: yarn commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose

      - name: Run ESLint check ğŸ”ï¸
        run: yarn lint

      - name: Run Prettier check ğŸ”ï¸
        run: yarn lint-prettier-ci

  test:
    needs: prepare-cache
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [18.x, 20.x, 22.x]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
        with:
          fetch-depth: 20
          fetch-tags: false

      - name: Setup codespace âš™ï¸
        uses: ./.github/actions/setup-codespace
        with:
          node-version: ${{ matrix.node-version }}
          os: ${{ matrix.os }}

      - name: Run unit tests ğŸ§ª
        run: yarn test

      - name: Run e2e tests ğŸ§ª
        run: yarn test-e2e

      - name: Run tests in example projects ğŸ§ª
        run: yarn test-examples

  test-performance:
    needs: prepare-cache
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
        with:
          fetch-depth: 20
          fetch-tags: false

      - name: Setup codespace âš™ï¸ï¸
        uses: ./.github/actions/setup-codespace
        with:
          os: ${{ runner.os }}

      - name: Build ğŸ—ï¸
        run: yarn build

      - name: Install dependencies ğŸ“¦
        run: yarn --cwd performance

      - name: Run Performance Tests ğŸ§ª
        run: yarn test-perf
