name: PR docs check ğŸ”

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed
    paths:
      - '.github/**/*'
      - 'website/**/*'

concurrency:
  group: preview-doc-pr-${{ github.event.pull_request.number }}
  cancel-in-progress: true

permissions:
  contents: write # Required to push commits
  pages: write # Required to deploy to Pages
  pull-requests: write # If creating/updating PRs

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkoutï¸ ğŸ›
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
        with:
          fetch-depth: 20
          fetch-tags: false

      - name: Setup docs workspace âš™ï¸
        uses: ./.github/actions/setup-docspace
        with:
          base-url: '/jest-preset-angular/pr-preview/pr-${{ github.event.pull_request.number }}/'

      - name: Deploy preview ğŸš€
        uses: rossjrw/pr-preview-action@55147b5848acb4ab980e55ff0bdc228addacdae0 # v1
        with:
          source-dir: ./website/build
