name: PR docs check ğŸ”

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed
    paths:
      - '.github/**/*'
      - 'website/**/*'

concurrency:
  group: preview-doc-pr-${{ github.event.pull_request.number }}
  cancel-in-progress: true

permissions:
  contents: write # Required to push commits
  pages: write # Required to deploy to Pages
  pull-requests: write # If creating/updating PRs

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkoutï¸ ğŸ›
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          fetch-depth: 20
          fetch-tags: false

      - name: Setup docs workspace âš™ï¸
        uses: ./.github/actions/setup-docspace
        with:
          base-url: '/jest-preset-angular/pr-preview/pr-${{ github.event.pull_request.number }}/'

      - name: Deploy preview ğŸš€
        uses: rossjrw/pr-preview-action@9f77b1d057b494e662c50b8ca40ecc63f21e0887 # v1
        with:
          source-dir: ./website/build
