name: Target branch check ğŸ”

on:
  push:
    branches:
      - main
      - next
    paths:
      - '**/*'
      - '!website/**/*'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  prepare-codespace:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [18.x, 20.x, 22.x]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 20
          fetch-tags: false

      - name: Setup codespace for ${{ matrix.os }} on Node v${{ matrix.node-version }} âš™ï¸
        uses: ./.github/actions/setup-codespace
        with:
          node-version: ${{ matrix.node-version }}
          os: ${{ matrix.os }}

      - name: Build project ğŸ”¨
        run: yarn build

  test:
    needs: prepare-codespace
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [18.x, 20.x, 22.x]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 20
          fetch-tags: false

      - name: Setup codespace âš™ï¸
        uses: ./.github/actions/setup-codespace
        with:
          node-version: ${{ matrix.node-version }}
          os: ${{ matrix.os }}

      - name: Run tests in CommonJS mode ğŸ§ª
        run: yarn test

      - name: Run tests in ESM mode ğŸ§ª
        run: yarn test-esm

      - name: Run tests in example projects ğŸ§ª
        run: yarn test-examples
